Project 200 completed
FRC5190/2020Training pull request #15
Opened 2019-10-01 23:12 UTC by ArnavSug

2019-10-02 13:33 UTC, prateekma requested changes
Please remove the .DS_Store files.

2019-10-05 13:54 UTC, ArnavSug commented
Removed the .DS_Store files. Can you take a look again @prateekma

2019-10-05 18:52 UTC, prateekma commented
@ArnavSug thank you!

2019-10-05 18:52 UTC, prateekma approved these changes

2019-10-05 18:53 UTC, merged